" ==============================================================================
" ~/.config/vim/vimrc
" ==============================================================================

filetype on
filetype indent on
filetype plugin on

hi CursorLine cterm=NONE ctermbg=darkgray
hi CursorLineNr cterm=bold
hi LineNr ctermfg=darkgray

" NetRw configuration:
let g:netrw_altv = 1
let g:netrw_banner = 0
let g:netrw_browse_split = 4
let g:netrw_hide = 1
let g:netrw_liststyle = 3
let g:netrw_preview = 1
let g:netrw_winsize = 20

nnoremap <silent> \e :Lexplore<cr>

set cursorline
set nohlsearch
set incsearch
set laststatus=2
set nocompatible
set nowrap
set number
set numberwidth=4
set showcmd
set showmatch
set showmode
set smartindent
" set termguicolors
set viminfo+=n~/.cache/viminfo
set wildmenu
set wildmode=list:longest
set wildignore=*.docx,*.jpg,*.png,*.gif,*.pdf,*.pyc,*.exe,*.flv,*.img,*.xlsx

augroup netrw_close
	autocmd!
	autocmd WinEnter * if winnr('$') == 1 && getbufvar(winbufnr(winnr()), "&filetype") == "netrw"|q|endif
augroup END

syntax on
