# ==============================================================================
# ~/.config/bash/bashrc
# ==============================================================================

# If not running interactively, don't do anything:
case $- in
    *i*) ;;
      *) return;;
esac

CDPATH=".:${HOME}"
BASH_CACHE_DIR="${XDG_CACHE_HOME}/bash"
BASH_CONFIG_DIR="${XDG_CONFIG_HOME}/bash"

# Shell options:
# ------------------

shopt -s autocd        # cd by just entering the directory path
shopt -s checkwinsize  # Check terminal window size after each command
shopt -s extglob
shopt -s globstar
shopt -s histappend    # Append to histfile, don't overwrite

# History configuration:
# ------------------

HISTCONTROL=ignoredups # Ignore duplicates, and those starting with whitespace
HISTFILE="${BASH_CACHE_DIR}/history"
HISTFILESIZE=2000      # Maximum number of commands allowed in histfile
HISTSIZE=2000          # Maximum number of commands remembered
HISTTIMEFORMAT="%c "   # Time format used by history

# Setup lesspipe:
# ------------------

if [ -x /usr/bin/lesspipe ]; then
	eval "`SHELL=/bin/sh /usr/bin/lesspipe`"
fi

# Set prompt:
# ------------------

PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
PS2='	\[\033[01;33m\]>>\[\033[00m\] '

# Enable color support:
# ------------------

if [ -x /usr/bin/dircolors ]; then
	if [ -r "$DIRCOLORS" ]; then
		eval "`/usr/bin/dircolors -b $DIRCOLORS`"
	else
		eval "`/usr/bin/dircolors -b`"
	fi
fi

# Include aliases:
# ------------------

if [ -f "${BASH_CONFIG_DIR}/aliases" ]; then
	. "${BASH_CONFIG_DIR}/aliases"
fi

# Enable bash completion:
# ------------------

if ! shopt -oq posix; then
	if [ -f /usr/share/bash-completion/bash_completion ]; then
		. /usr/share/bash-completion/bash_completion
	elif [ -f /etc/bash_completion ]; then
		. /etc/bash_completion
	fi
fi
